update_logs: True
update_to_last_minute: True
split_logs_to_games: True
create_analysis: True
create_monthly_plots: True
extract_player_plot: True
make_stats: False
overwrite_game_logs: False
focus_player: '76561198006728045'

metrics: [list Apolo kpm,list kpm,list dpm]
